config/routes.rb
# encoding: utf-8
# frozen_string_literal: true

Renopertyadmin::Engine.routes.draw do
  root to: 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'

  resources :users, only: %w[index edit update] do
    member do
      get 'sign_in_as_user'
      get 'ploxy_sign_in_as_user'
      patch 'account_lock'
      patch 'account_unlock'
      patch 'block_mails'
    end
    collection do
      get 'user_display'
      get 'sub_accounts_index'
    end
  end

  resources :companies

  resources :properties
end

app/models/renopertyadmin/application_record.rb
module Renopertyadmin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/renopertyadmin/application_controller.rb
# engoding: utf-8
# frozen_string_literal: true

module Renopertyadmin
  class ApplicationController < ::ApplicationController
    include Accessible

    protect_from_forgery with: :exception

    # デフォルトレイアウトの指定
    layout 'renopertyadmin/application'

    # 起点復元リダイレクトの施策
    include Redirectable
    before_action :keep_back_to_path
    helper_method :back_to_param, :back_to_hidden_tag, :back_to_path
  end
end

app/controllers/renopertyadmin/companies_controller.rb
# encoding: utf-8
# frozen_string_literal: true

module Renopertyadmin
  class CompaniesController < ApplicationController

    def new
      @company = Company.new
    end

    def create
      @company = Company.new(company_params)
      if @company.save
        redirect_to companies_path
      else
        render :new
      end
    end

    def edit
      @company = Company.find(params[:id])
    end

    def update
      @company = Company.find(params[:id])
      if @company.update_attributes!(company_params)
        flash[:success] = t('msg.update_successful', v: t('company'))
        redirect_to companies_path
      else
        flash.now[:error] = t('msg.error_in_the_input_content')
        render 'new'
      end
    end

    def index
      @companies = Company.all.paginate(page: params[:page], per_page: 30)
    end

    private

    def company_params
      params.required(:company).permit(
        :address, :name, :tel, :establishment, :description, :deleted, :ward_id,
        :public, :company_size_id
      )
    end

  end
end

app/controllers/renopertyadmin/dashboard_controller.rb
require_dependency 'renopertyadmin/application_controller'

module Renopertyadmin
  class DashboardController < ApplicationController
    def index
      render :index, layout: 'renopertyadmin/application'
    end
  end
end

app/controllers/renopertyadmin/properties_controller.rb
# encoding: utf-8
# frozen_string_literal: true

module Renopertyadmin
  class PropertiesController < ApplicationController

    def new
      @property = Property.new
    end

    def create
      @property = create_new_property
      if @property.save
        redirect_to properties_path
      else
        render :new
      end
    end

    def edit
    end

    def index
      @properties = Property.all.paginate(page: params[:page], per_page: 12)
    end

    private

    def create_new_property
      new_property = Property.new(property_params)
      new_property.property_type = convert_property_type
      new_property.area_id = convert_area_id
      new_property.layout = convert_layout
      new_property.balcony_direction = convert_balcony_direction
      new_property
    end

    # Serializeに対応するため、型をconvert
    def convert_property_type
      property_params[:property_type].present? ? property_params[:property_type].split : []
    end

    def convert_area_id
      property_params[:area_id].present? ? property_params[:area_id].split : []
    end

    def convert_layout
      property_params[:layout].present? ? property_params[:layout].split : []
    end

    def convert_balcony_direction
      property_params[:balcony_direction].present? ? property_params[:balcony_direction].split : []
    end

    def property_params
      params.required(:property).permit(
        :property_name, :prefecture_id, :area, :address, :price, :layout, :exclusive_area_size, :floore_level,
        :completion_date, :property_type, :balcony_size, :balcony_direction, :total_number_of_houses,
        :rights_concening_land, :management_company, :management_fee, :repair_reserve_fund, :handover_date,
        :transportation, :area_id
      )
    end
  end
end

app/controllers/renopertyadmin/users_controller.rb
# encoding: utf-8
# frozen_string_literal: true

module Renopertyadmin
  class UsersController < ApplicationController

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to users_path
      else
        render :new
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def index
      @users = User.all.paginate(page: params[:page], per_page: 12)
    end

    private

    def user_params
      params.required(:user).permit(
      )
    end

  end
end

app/helpers/renopertyadmin/application_helper.rb
module Renopertyadmin
  module ApplicationHelper
  end
end

app/helpers/renopertyadmin/companies_helper.rb
module Renopertyadmin
  module CompaniesHelper
  end
end

app/helpers/renopertyadmin/properties_helper.rb
module Renopertyadmin
  module PropertiesHelper
  end
end

app/views/layouts/renopertyadmin/_footer.html.slim
/ コピーライト表示年の自動更新
- year = Date.today.year
footer.page-footer.center-on-small-only.pt-0.mt-5
  .footer-copyright
    .container-fluid
      | ©︎#{year} Copyright:
      a[href="https://renoperty.jp"]
        | Renoperty

app/views/layouts/renopertyadmin/_side_navi.html.slim
.card.side-menu-contents.p-3
  ul.collapsible.collapsible-accordion.list-unstyled
    li
      = active_link_to root_path, class: 'collapsible-header waves-effect arrow-r py-2 px-3 d-block', :active => [['renopertyadmin/dashboard'], ['index']] do
        i.fas.fa-tachometer-alt.pr-3
        | Dashboard
    li
      = active_link_to 'javascript:void(0)', class: 'collapsible-header waves-effect arrow-r py-2 px-3 d-block', :active => [['renopertyadmin/users', 'renopertyadmin/companies'], ['index']] do
        i.fa.fa-user.pr-3
        | User
        i.material-icons.rotate-icon.md-grey
          | keyboard_arrow_down
      .collapsible-body
        ul
          li = active_link_to users_path, class: 'waves-effect py-2 px-3 d-block' do
            | User
          li = active_link_to companies_path, class: 'waves-effect py-2 px-3 d-block' do
            | Company
    li
      = active_link_to 'javascript:void(0)', class: 'collapsible-header waves-effect arrow-r py-2 px-3 d-block', :active => [['renopertyadmin/properties'], ['index']] do
        i.far.fa-handshake.pr-3
        | Bizmatch
        i.material-icons.rotate-icon.md-grey
          | keyboard_arrow_down
      .collapsible-body
        ul
          li = active_link_to properties_path, class: 'waves-effect py-2 px-3 d-block' do
            | Property

app/views/layouts/renopertyadmin/_top_menu.html.slim
nav.navbar.fixed-top.navbar-toggleable-md.navbar-expand-lg.scrolling-navbar.double-nav.white
  .breadcrumb-dn.mr-auto
    p
      | Renoperty Admin console
  ul.nav.navbar-nav.nav-flex-icons.ml-auto
    li.nav-item.dropdown
      a#userDropdown.nav-link.dropdown-toggle.waves-effect.black-text[href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
        i.fa.fa-user
        span.clearfix.d-none.d-sm-inline-block
          | Profile
      .dropdown-menu.dropdown-menu-right[aria-labelledby="userDropdown"]
      // TODO: 正確なpath設定する
        = link_to 'Log out', main_app.destroy_admin_user_session_path, class: 'dropdown-item', method: 'delete'
        = link_to 'My account', main_app.destroy_admin_user_session_path, class: 'dropdown-item'

app/views/layouts/renopertyadmin/application.html.slim
doctype html
html
  head
    meta[charset='UTF-8']
    meta[name='viewport' content='width=devise-width, initial-scale=1, shrink-to-fit=no']
    meta[http-equiv='x-ua-compatible' content='ie=edge']
    meta[http-equiv='content-language' content='ja']
    title
      | Renoperty Admin console

    = csrf_meta_tags
    = stylesheet_link_tag 'mdb'
    = stylesheet_link_tag 'renopertyadmin/application'
    = stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.7.2/css/all.css'
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = stylesheet_link_tag "/assets/environment/#{Rails.env}"
    = yield :js
    = yield :css

  body.pt-5

    / header tag start
    header
      /! fixed top menu start
      = render :partial => 'layouts/renopertyadmin/top_menu'
      /! fixed top menu end
    / header tag end

    /! main contents start
    main
      .container-fluid
        - flash_messages
        .row
          .col-3
            = render :partial => 'layouts/renopertyadmin/side_navi'
          .col
            = yield
    /! main contents end

    / footer tag start
    = render :partial => 'layouts/renopertyadmin/footer'
    / footer tag end

    /! common scripts start
    = javascript_include_tag 'renopertyadmin/application'
    - if browser.ie?
      = javascript_include_tag 'mdb4.7.6/mdb.min'
    - else
      = javascript_include_tag 'mdb.min'
    = yield :local_js
    /! common scripts end

    /! SideNav Initialization
    javascript:
      #{flash_messages}

app/views/renopertyadmin/companies/_form.html.slim
= form_for @company, url: get_company_form_for_url(@company), builder: FormHelper::OriginalFormBuilder do |f|
  .card.px-3.px-md-4.form-card.mt-2.pt-5
    .pl-0.pl-sm-2.border-bottom.mb-5
      .row.px-3
        .col-6
          = f.text_field :address
        .col-6
          = f.single_dropdown_list :ward_id, Company.ward_id.options(selected: @company.ward_id), {include_blank: 'please_select'}, {required: true}
    .pl-0.pl-sm-2
      .row.px-3
        .col-6
          = f.text_field :name
        .col-6
          = f.text_field :tel
      .row.px-3
        .col-6
          = f.single_dropdown_list :public, Company.public.options(selected: @company.public), {include_blank: 'please_select'}, {required: true}
        .col-6
          = f.text_field :establishment
      .row.px-3
        .col-6
          = f.text_area :description
        .col-6
          = f.single_dropdown_list :company_size_id, Company.company_size_id.options(selected: @company.company_size_id), {include_blank: 'please_select'}, {required: true}

  .row.justify-content-md-center.mt-5
    .col-12.col-md-4.mt-2
      = f.button t('Regist'), type: 'submit', class: 'btn btn-deep-orange btn-block btn-lg font-extralarge'

app/views/renopertyadmin/companies/edit.html.slim
= render partial: 'form'

app/views/renopertyadmin/companies/index.html.slim
/* 新規登録ボタン
.row
  .md-form.col-12.mb-4
    = link_to new_company_path, class: 'btn btn-lg btn-deep-orange m-0 font-middle'
      i.material-icons.font-extralarge.mr-3.vertical-sub
        | insert_drive_file
      span = t('regist_new_company')

/* ヒットしたレコード数表示
.row
  .col-12
    = hit_records(@companies.total_entries.to_s(:delimited))

/* レコード中身表示
.m-3
section
  .card
    .card-body
      table.table.table-striped
        thead.mdb-color.darken-3
          tr.text-white
            th
              | #{t('name')}
            th
              | #{t('status')}
            th
              | #{t('edit')}
        tbody
          - @companies.each do |company|
            tr
              td[scope='row']
                =<> "#{company.name}"
              td
                = delete_display_setting(company.deleted)
              td.text-center
                = link_to '', edit_company_path(company, back_to_param), class: 'i fa fa-wrench fa-lg'

.row
  - @companies.each do |company|
    = render partial: 'manage_summary', :locals => {company: company, attention: false}

app/views/renopertyadmin/companies/new.html.slim
h4 = 'Create New Comapany record'
= render partial: 'form'

app/views/renopertyadmin/dashboard/index.html.slim
h1 Dashboars#index
p Find me in app/views/renopertyadmin/dashboard/index.html.slim

app/views/renopertyadmin/properties/_form.html.slim
= form_for @property, url: get_property_form_for_url(@property), builder: FormHelper::OriginalFormBuilder do |f|
  .card.px-3.px-md-4.form-card.mt-2.pt-5
    .pl-0.pl-sm-2.border-bottom.mb-5
      .row.px-3
        .col-6
          = f.text_field :property_name
        .col-6
          = f.text_field :address
    .pl-0.pl-sm-2
      .row.px-3
        .col-6
          = f.text_field :price, {required: true}
        .col-6
          = f.text_field :exclusive_area_size, {required: true}
      .row.px-3
        .col-6
          = f.text_field :floore_level
        .col-6
          = f.date_field :completion_date, {required: true}
      .row.px-3
        .col-6
          = f.single_dropdown_list :property_type, Property.property_type.options(selected: @property.property_type), {include_blank: 'please_select'}, {required: true}
        .col-6
          = f.single_dropdown_list :area_id, Property.area_id.options(selected: @property.area_id), {include_blank: 'please_select'}, {required: true}
      .row.px-3
        .col-6
          = f.single_dropdown_list :layout, Property.layout.options(selected: @property.layout), {include_blank: 'please_select'}, {required: true}
        .col-6
          = f.text_field :balcony_size
      .row.px-3
        .col-6
          = f.single_dropdown_list :balcony_direction, Property.balcony_direction.options(selected: @property.balcony_direction), {include_blank: 'not_selected'}
        .col-6
          = f.text_field :total_number_of_houses
      .row.px-3
        .col-6
          = f.single_dropdown_list :rights_concening_land, Property.rights_concening_land.options(selected: @property.rights_concening_land), {include_blank: 'please_select'}, {required: true}
        .col-6
          = f.text_field :management_company
      .row.px-3
        .col-6
          = f.text_field :management_fee
        .col-6
          = f.text_field :repair_reserve_fund
      .row.px-3
        .col-6
          = f.date_field :handover_date
        .col-6
          = f.text_field :transportation

  .row.justify-content-md-center.mt-5
    .col-12.col-md-4.mt-2
      = f.button t('Regist'), type: 'submit', class: 'btn btn-deep-orange btn-block btn-lg font-extralarge'

app/views/renopertyadmin/properties/_manage_summary.html.slim
.col-12.col-md-6.col-xl-4.d-flex
  .card.mb-4.w-100.hoverable
    = link_to edit_property_path(property.id)
      .card-header
        h5.mb-0.font-middle.float-left
          span.d-block.mb-1
            = property.property_name.truncate(15)
        i.material-icons.md-light.d-block.text-right
          | description

    .card-content
      .row
        .col-12.col-sm-6.col-md-12
          .mb-3
            label.custom-grey-text.mb-0 #{t('registered_date')}
            = property.created_at

app/views/renopertyadmin/properties/index.html.slim
/* 新規登録ボタン
.row
  .md-form.col-12.mb-4
    = link_to new_property_path, class: 'btn btn-lg btn-deep-orange m-0 font-middle'
      i.material-icons.font-extralarge.mr-3.vertical-sub
        | insert_drive_file
      span = t('regist_new_property')

/* ヒットしたレコード数表示
.row
  .col-12
    = hit_records(@properties.total_entries.to_s(:delimited))

/* レコード中身表示
.row
  - @properties.each do |property|
    = render partial: 'manage_summary', :locals => {property: property, attention: false}

app/views/renopertyadmin/properties/new.html.slim
h4 = 'Create New Property record'
= render partial: 'form'

app/views/renopertyadmin/users/index.html.slim
/* ヒットしたレコード数表示
.row
  .col-12
    = hit_records(@users.total_entries.to_s(:delimited))

/* レコード中身表示
.m-3
section
  .card
    .card-body
      table.table.table-striped
        thead.mdb-color.darken-3
          tr.text-white
            th
              | #{t('name')}
            th
              | #{t('status')}
            th
              | #{t('edit')}
        tbody
          - @users.each do |user|
            tr
              td[scope='row']
                =<> "#{user.name}"
              td
                = delete_display_setting(user.deleted)
              td.text-center
                = link_to '', edit_user_path(user, back_to_param), class: 'i fa fa-wrench fa-lg'

.row
  - @users.each do |user|
    = render partial: 'manage_summary', :locals => {property: property, attention: false}